In [8]:
L1 = [ 10,20, 30,25, 32, 45,50]
L2 = [ 80,70,78,55,62]
print(sum(L1))
print(sum(L2))



212
345


In [12]:
import math


In [14]:
math.sqrt(16)

4.0

In [16]:
math.pow(2,5)

32.0

In [20]:
import calendar


In [26]:
cal = calendar.month(2025, 3)
print(cal)
cal = calendar.month(2025, 4)
print (cal)

     March 2025
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

     April 2025
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30



In [28]:
dir(calendar)

['APRIL',
 'AUGUST',
 'Calendar',
 'DECEMBER',
 'Day',
 'EPOCH',
 'FEBRUARY',
 'FRIDAY',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'IntEnum',
 'JANUARY',
 'JULY',
 'JUNE',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MARCH',
 'MAY',
 'MONDAY',
 'Month',
 'NOVEMBER',
 'OCTOBER',
 'SATURDAY',
 'SEPTEMBER',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_get_default_locale',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'global_enum',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',

In [37]:
def fun():
    print("welcome to Dphi")


# Assistant
The selected code defines a recursive function that will cause a stack overflow. Here's a step-by-step explanation:

1. `def fun():` - This line defines a new function named `fun` that takes no parameters.

2. `print("welcome to Dphi")` - Inside the function, this line prints the string "welcome to Dphi".

3. `fun()` - This line calls the `fun` function from within itself, creating a recursive call with no base case or exit condition.

This is problematic because each time `fun()` is called, it will print the message and then call itself again, creating an infinite recursion. Without a base case to stop the recursion, this will eventually cause a "RecursionError: maximum recursion depth exceeded" when the call stack gets too deep.

In [39]:
    fun()

welcome to Dphi


In [43]:
def add(num1:int, num2:int) ->int:
    #Add two numbers 
    num3 = num1+num2
    return num3
    

In [47]:
num1, num2 = 5, 15
ans = add(num1, num2)
print(f"the addition of {num1} and {num2} results {ans}.")


the addition of 5 and 15 results 20.


In [52]:
python_list =[2,4,6,8,10]

In [54]:
python_list

[2, 4, 6, 8, 10]

# Assistant
The selected code performs a simple addition operation and prints the result. Here's a step-by-step explanation:

1. `num1, num2 = 5, 15` - This line assigns the value 5 to the variable `num1` and 15 to the variable `num2` using multiple assignment.

2. `ans = add(num1, num2)` - This line calls a function named `add` with the arguments `num1` and `num2`, and assigns the returned result to the variable `ans`. Note that the `add` function must be defined elsewhere in the code.

3. `print("the addition of {num1} and {num2} results {ans}.")` - This line attempts to print a formatted string, but there's an issue: it uses curly braces without f-string notation. To properly display the variable values, it should be written as `f"the addition of {num1} and {num2} results {ans}."` with an 'f' prefix.

In [74]:
import numpy as np

In [76]:
numpy_array1 = np.array(python_list)
#Display the numpy array


In [78]:
numpy_array1


array([ 2,  4,  6,  8, 10])

In [80]:
# Create two python List say 'List_x' and 'List_your'
X_list = list(range(100000))
Y_list = list(range(100000))

In [82]:
# Import numpy Library
import numpy as np
# Create two numpy array (say 'X' end 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)

In [84]:
# Define a function to calculate sum
# using python Lists X_list, Y_list)
def pure_python_version():
    Z = []
    for i in range(len(X_list)):
        Z.append(X_list[i] + Y_list[i])

In [86]:
# Define a function to calculate sum
# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform
# sum element-wise as
    Z = X + Y 

In [88]:
# Import Timer class from timeit Library
from timeit import Timer

In [90]:
timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print("Pure python version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

Pure python version: 12.875965575998634
Numpy version: 0.19206730199948652


In [92]:
#Import Numpy Library
import numpy as np


In [96]:
arr = np.array([[5,6,7], [11,12,13], [1,2,3]])


In [98]:
arr

array([[ 5,  6,  7],
       [11, 12, 13],
       [ 1,  2,  3]])

In [102]:
arr.size


9

In [104]:
arr.dtype


dtype('int64')

In [106]:
arr.shape

(3, 3)

In [108]:
arr.ndim

2

In [110]:
#Create a Python List 
python_list = [1,2,3,4]


In [112]:
type(python_list)

list

In [114]:
list = [2, 5, 8, 6, 4, 12, 16, 15]


In [118]:
# a list of programming languages
['Python', 'C++', 'JavaScript']

['Python', 'C++', 'JavaScript']

In [120]:
# list of integers
my_list = [1, 2, 3]

In [122]:
# list with mixed data types
my_list = [9, "Espanol", 4.6, ['a','b','c']]
print(my_list)

[9, 'Espanol', 4.6, ['a', 'b', 'c']]


In [124]:
# nested list
my_list = ["mouse", [8, 4, 6], ['a']]
print(my_list)

['mouse', [8, 4, 6], ['a']]


In [126]:
# An array of integers.
print([1, 2, 3, 4, 5])

# An array of strings.
print([ 'a', 'b', 'c', 'd', 'e' ])

# A 2 dimensional array.
print([[ 1 , 2 , 3 , 4],
[ 5, 6, 7, 8 ]])

[1, 2, 3, 4, 5]
['a', 'b', 'c', 'd', 'e']
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [128]:
heights = [165, 170, 171, 180, 189, 178]
print(type(heights))

heights_np = np.array(heights)
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>


In [130]:
import numpy as np


In [132]:
heights = [165, 170, 171, 180, 189, 178]
print(type(heights))

heights_np = np.array(heights)
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>


In [134]:
weights = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])
print(weights)

[[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]


In [136]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [138]:
print("dimension:", weights.ndim)
print("shape:", weights.shape)
print("size:", weights.size)
print("dtype:", weights.dtype)
print("strides:", weights.strides)

dimension: 2
shape: (6, 4)
size: 24
dtype: int64
strides: (32, 8)


In [140]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [142]:
# Creating a 3X5 array with all zeros
x = np.zeros(shape=(3,5), dtype ="int32")
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [144]:
# Creating an array of complex type having constant values
constant = np.full((4, 4), fill_value=5, dtype = 'complex')
print ("\nA complex array initialized with all 5s.", constant)


A complex array initialized with all 5s. [[5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j]]


In [146]:
# Create an array with random values
e = np.random.random((4, 4))
print ("\nA random array:\n", e)


A random array:
 [[0.75263837 0.1309743  0.62088413 0.54653336]
 [0.1685628  0.5216655  0.96580668 0.41741468]
 [0.69011509 0.17393083 0.84744369 0.13057098]
 [0.42832151 0.17819353 0.13614854 0.59905223]]


In [148]:
# Create a sequence of integers from 100 to 1000 with steps of 100
f = np.arange(start=100, stop=1000, step=100, dtype="int32")
print ("\nA sequential array with steps of 100:\n", f)


A sequential array with steps of 100:
 [100 200 300 400 500 600 700 800 900]


In [150]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
"0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [152]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])

newarr = arr.reshape(2, 6, 2)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]
Reshaped array:
 [[[50 45]
  [56 78]
  [78 89]
  [59 90]
  [89 78]
  [69 70]]

 [[67 69]
  [89 70]
  [90 89]
  [80 84]
  [89 59]
  [90 78]]]


In [154]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
