In [2]:
import numpy as np


In [4]:
arr = np.array([10,20,30,40])

In [6]:
arr

array([10, 20, 30, 40])

In [10]:
arr[2]

30

In [12]:
arr = np.array([10,20,30,40])

In [14]:
arr[-2]

30

In [16]:
#Introduction to Numpy 2
#This is the second Notebook of the course Introduction to Numpy This notebooks covers the following topics

#Attributes of an array and creating basic array

#Basic Methods as append,remove,sort

#Indexing and slicing


#This is the second Notebook of the course Introduction to Numpy This notebooks covers the following topics

#Attributes of an array and creating basic array
#Basic Methods as append,remove,sort
#Indexing and slicing


In [18]:
import numpy as np
a = np.array([7, 6, 8, 9])
print(a)

[7 6 8 9]


In [20]:
# adding 3 to every element
a = np.array([7, 6, 8, 9])
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [ 8  7  9 10]


In [22]:
# subtracting 4 from each element
a = np.array([7, 6, 8, 9])
print("Subtracting 3 from each element:", a-4)

Subtracting 3 from each element: [3 2 4 5]


In [24]:
# multiply each element by 10
a = np.array([7, 6, 8, 9])
print ("Multiplying each element by 5:", a*5)

Multiplying each element by 5: [35 30 40 45]


In [26]:
# squaring each element of the array
print ("Squaring each element:", a**2)

Squaring each element: [49 36 64 81]


In [28]:
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

Doubled each element of original array: [14 12 16 18]


In [30]:
# transpose of array
a = np.array([[3, 1, 2], [6, 5, 4], [7, 9, 8]])

print ("\nOriginal array is:\n", a)
print ("Transpose of array is:\n", a.T)


Original array is:
 [[3 1 2]
 [6 5 4]
 [7 9 8]]
Transpose of array is:
 [[3 6 7]
 [1 5 9]
 [2 4 8]]


In [32]:
#Append
arr = np.array([1,9,8,4,5,6])
np.append(arr,7)

array([1, 9, 8, 4, 5, 6, 7])

In [34]:
#Adding an element to a Python list using np.append() method. But the returned object is a NumPy array.
l = [2,3,5,4,7,6]
arr = np.append(l,10)
arr

array([ 2,  3,  5,  4,  7,  6, 10])

In [36]:
np.append(arr, [11, 22])

array([ 2,  3,  5,  4,  7,  6, 10, 11, 22])

In [38]:
arr = np.array([2,5,8,9,7,6])
np.delete(arr,1) #removing the element at index 1

array([2, 8, 9, 7, 6])

In [40]:
#sorting an array of integers
arr = np.array([3, 2, 4, 1])
print(np.sort(arr))

[1 2 3 4]


In [42]:
#sorting an array alphabetically
arr = np.array(['Lamborghini', 'Porsche', 'Mercedes'])
print(np.sort(arr))

['Lamborghini' 'Mercedes' 'Porsche']


In [44]:
#sorting a 2-D array
arr = np.array([[5, 7, 8],
[6, 2, 3]])
print(np.sort(arr))

[[5 7 8]
 [2 3 6]]


In [46]:
#Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
array = np.where(arr == 4)
print(array)

(array([3, 5, 6]),)


In [48]:
#Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [50]:
# Indexing and Slicing
#Array indexing
#To access the content of an array we can use indexing through brackets [ ]. When using the brackets, we can access the elements on the list by:

#Using a positive single index starting from 0
#Using a negative single index starting from -1
#Using positive index intervals using the start:end:step notation to specify starting and ending values as well as the step.
#Using negative index intervals using the start:end:step notation to specify negative index starting and ending values as well as the step.
#Occasionally, we can:

#Get ride of the the step value as sart:end, so that by default we slice the data with a step of 1.
#Get ride of the start value as :fin:step, and hence our start index will be 0, by default.
#Omit the end value as start::step, specifying the final position as the end index by default.
#Specify the range as ::step, and hence the start position will be 0 and the end position will be the last one of the array. Let's see how indexing works using the weights and heights_np arrays:
#Array Indexing

#Accessing Array elements from 1-D array 

In [52]:
# Get the first element from the following array:
import numpy as np
arr = np.array([9, 8, 4, 5])
print(arr[0])

9


In [54]:
import numpy as np
arr = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [56]:
#Slicing arrays
#Slicing in python means taking elements from one given index to another given index.

#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
#If we don't pass start its considered 0
#If we don't pass end its considered length of array in that dimension
#If we don't pass step its considered 

In [58]:
# Slicing elements from index 3 to index 7 in the following array:
arr = np.array([22, 81, 23, 34, 56, 63, 71])
print(arr[1:5])

[81 23 34 56]


In [60]:
# printing elements from index 4 to the end of the array using slicing
arr = np.array([22, 81, 23, 34, 56, 63, 71])
print(arr[4:])

[56 63 71]


In [62]:
# Slice elements from the beginning to index 5 (not included):
arr = np.array([22, 81, 23, 34, 56, 63, 71])
print(arr[:5])

[22 81 23 34 56]


In [64]:
#Return every second element from index 1 to index 5 :
arr = np.array([22, 81, 23, 34, 56, 63, 71])
print(arr[1:5:2])

# [81, 23, 34, 56, 63] start from 81 and print elements at a distance of 2 from starting position

[81 34]


In [66]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [68]:
#Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [70]:
#From both elements, return index 2:
arr = np.array([[1, 2, 4, 5, 3], [9, 8, 7, 6, 1]])
print(arr[0:2, 2])


[4 7]


In [72]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [74]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [76]:
#printing the last two elements
arr = np.array([0, 1, 2, 3, 6, 7, 8, 9])
print(arr[-2:])

[8 9]


In [78]:
print(arr[-3:3:-1])

[7 6]
